### ISSUE TITLE
H36M annotation

### ISSUE THREAD

**Issue by KenkunLiu** [yufu-wang/ReFit#2]
Thank you for this great work, can you provide more details about how to obtain h36m annotation that you used for training? I am trying to train the model in my own machine.

**Comment by yufu-wang** [comment]
Thanks for reaching out!
The annotation format is compatible with SPIN. So you can refer to this file from SPIN to preprocess H36M
(https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/h36m_train.py)
However, it would come with the SMPL parameters, as stated here (https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md)

**Comment by KenkunLiu** [comment]
Ok, I will try it. Thanks!

**Comment by KenkunLiu** [comment]
Now I can get process H36M annotations with the guidance in SPIN, but I still do not know how to get SMPL parameters for H36M，can you provide more details?

**Comment by yufu-wang** [comment]
The SMPL parameters for H36M was original released by HMR (by running MoSH) but has since been retracted due to licensing issues. We cannot share it for the same reason. But you can still use the 2D&3D keypoints from H36M as supervision. You can also replicate the experiment that only uses BEDLAM + AGORA for training.

**Comment by yufu-wang** [comment]
I uploaded the H36M annotations to the GoogleDrive, along with the others annotations. I will close this issue for now. Let me know if you have other questions.
